sdk: "C:/Neon/git/rhodes"
#sdk: ../../
paths:
  extensions:
   - C:/Neon/git/rhodes/lib/commonAPI
   - C:/Neon/git/Motorola-Extensions/lib/commonAPI
#Win8
   - C:/git/rhodes/lib/commonAPI
   - C:/git/Motorola-Extensions/lib/commonAPI
#   - C:/Neon/ClearCase/jrq768_Neon_Main/vobs/NEON/R2D1/RhoElementsOneExtension/extensions/
   - B:/git/rhodes/lib/commonAPI
   - B:/git/Motorola-Extensions/lib/commonAPI
   - B:/git/Motorola-Extensions/build/ci/extensions
sdkversion: 3.3.2
name: RE4TestApp
app_type: rhoelements
version: 1.0
vendor: rhomobile
build: debug
bbver: 4.6
applog: rholog.txt
iphone:
  configuration: Release
  sdk: iphonesimulator5.0
  provisionprofile:
  codesignidentity:
  entitlements:
  BundleIdentifier: com.rhomobile.apigeneratorspec
  BundleURLScheme: apigeneratorspec
wp:
  productid: 'b6479381-42a8-0130-78de-3caec51bd50e'
symbian:
  uid: '0xe1a1ef92'
android:
  version: 2.1
wm:
#  use_shared_runtime: yes
#sdk: "MC3000c50b (ARMV4I)"   
#  sdk: "Windows Mobile 6.5.3 Professional DTK (ARMV4I)"
  
  
#extensions: ["json", "barcode", "coreapi", "indicators", "hardware_keys"]
extensions: ["json", "barcode", "coreapi", "indicators", "hardwarekeys"]
#extensions: ["json", "barcode", "coreapi", "indicators", "camera"]
#extensions: ["json"]
capabilities:
#- motorola
#- motorola_browser
#- webkit_browser
#- non_motorola_device

#use_shared_runtime: 1
